# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    # Choose the version of Node you want here
    - image: cimg/node:18.17.1
  working_directory: ~/repo

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Run tests
          command: yarn test

  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install --frozen-lockfile
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      # Run semantic-release after all the above is set.
      - run:
          name: Publish to NPM
          command: yarn semantic-release

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - tests
      - publish:
          requires:
            - tests
          filters:
            branches:
              only: main
