# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install --frozen-lockfile

  tests:
    <<: *defaults
    steps:
      - run:
          name: Run tests
          command: yarn test

  publish:
    <<: *defaults
    steps:
      # - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      # Run semantic-release after all the above is set.
      - run:
          name: Publish to NPM
          command: yarn semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - setup
      - tests:
          requires:
            - setup
      - publish:
          requires:
            - tests
          filters:
            branches:
              only: main